keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: CollageERP
  resource: collage-erp-web
  public-client: true
  use-resource-role-mappings: true
  cors: true
  cors-max-age: 0
  principal-attribute: preferred_username
  cors-allowed-methods: POST, PUT, DELETE, GET
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers  
# eureka:
#   instance:
#     prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST_URL:127.0.0.1}
      port: ${MONGO_DB_HOST_PORT:27017}
      authentication-database: admin
